version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=/var/lib/localstack/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/var/lib/localstack/data
    ports:
      - "4570:4566"
      - "4571:4571"
      - "8080:8080"

volumes:
  localstack_data:
